wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.26
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      3:
      - 1
      4: 3.9.2
      5: 0.10.26
      8:
      - 3
      - 5
attribute:
  desc: null
  value: all
batch_size:
  desc: null
  value: 8
checkpoint:
  desc: null
  value: checkpoint/1_multi_task_unet
image_path:
  desc: null
  value: data/task2_h5/
jaccard_weight:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.001
model_weight:
  desc: null
  value: null
n_epochs:
  desc: null
  value: 100
optimizer:
  desc: null
  value: Adam
resume_path:
  desc: null
  value: null
train_test_split_file:
  desc: null
  value: ./data/train_test_id.pickle
workers:
  desc: null
  value: 4
